---
- name: Converge
  hosts: all
  become: true
  tasks:
    - name: Include otel_collector_contrib
      ansible.builtin.include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
      vars:
        otel_collector_contrib_state: absent
