FROM {{ lookup('env', 'MOLECULE_IMAGE') }}

ENV container=docker

# Install systemd, python, ca-certificates, procps, and sudo if not present
RUN if [ -f /etc/redhat-release ]; then \
      dnf -y update; dnf -y install systemd python3 sudo ca-certificates procps-ng; dnf clean all; \
    elif [ -f /etc/debian_version ]; then \
      apt-get update && \
      apt-get install -y systemd systemd-sysv python3 sudo ca-certificates procps && \
      apt-get clean && \
      rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*; \
    elif [ -f /etc/arch-release ]; then \
      pacman -Sy --noconfirm systemd python sudo ca-certificates procps-ng; \
    fi

# Mask unwanted services globally
RUN systemctl mask systemd-tmpfiles-setup.service systemd-update-utmp.service

# Create ansible user
RUN useradd -m -s /bin/bash ansible && \
    echo "ansible ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

# Ensure /lib/systemd/systemd exists (symlink if needed) so we can use a consistent command
RUN if [ ! -e /lib/systemd/systemd ]; then \
      if [ -e /usr/lib/systemd/systemd ]; then \
        ln -s /usr/lib/systemd/systemd /lib/systemd/systemd; \
      fi; \
    fi

# Start systemd
CMD ["/lib/systemd/systemd"]
